### ISSUE TITLE
Watch hangs after a while and new event don't trigger expected actions

### ISSUE THREAD

**Issue by vitobotta** [spoved/kube-client.cr#12]
Hi! I am using this shard in https://github.com/vitobotta/velero-notifications - a controller to send notifications for Velero backups.

The "watch" for the CRD for the backups works for a while then it kinda hangs or something because new events are not picked up. Is there a way to automatically reconnect to the API and restart the watch when something goes wrong with the connection? Thanks!

**Comment by kalinon** [comment]
@vitobotta hello! i checked out your repo, that seems to be a Ruby repo. This is the Crystal-Lang shard for K8S.

Are you sure your in the right place? If you are, i would love to see your example code. I will try to reproduce it either way.

**Comment by vitobotta** [comment]
Hi @kalinon sorry  for the confusion, I reverted to the Ruby version while testing some stuff. I will create another repo for the Crystal version shortly. :)

**Comment by vitobotta** [comment]
@kalinon the Crystal version is here https://github.com/vitobotta/velero-notifications-crystal

**Comment by kalinon** [comment]
@vitobotta i was able to run this for a few hours and i did notice that the watch does seem to timeout after 10 minutes, and it gets a "End of file reached" error. But the client performs a reconnect and things keep going.

```
2023-04-29T16:17:47.046965Z  DEBUG - http.client: Performing request -- method: "GET", host: "ubu", port: 54977, resource: "/api/v1/namespaces/kube-system/pods?watch=true"
2023-04-29T16:17:47.089219Z   INFO - ADDED coredns-77ccd57875-q8lrh
2023-04-29T16:17:47.092168Z   INFO - ADDED helm-install-traefik-crd-vcl4j
2023-04-29T16:17:47.093934Z   INFO - ADDED helm-install-traefik-ntxns
2023-04-29T16:17:47.093938Z   INFO - ADDED svclb-traefik-ead43597-ph2qt
2023-04-29T16:17:47.095235Z   INFO - ADDED metrics-server-54dc485875-b7576
2023-04-29T16:17:47.096922Z   INFO - ADDED traefik-84745cf649-92pgw
2023-04-29T16:17:47.096927Z   INFO - ADDED local-path-provisioner-957fdf8bc-z6m4k
2023-04-29T16:25:01.988769Z   INFO - MODIFIED local-path-provisioner-957fdf8bc-z6m4k
2023-04-29T16:25:02.001284Z   INFO - ADDED local-path-provisioner-957fdf8bc-q9ttw
2023-04-29T16:25:02.012135Z   INFO - MODIFIED local-path-provisioner-957fdf8bc-q9ttw
2023-04-29T16:25:02.036917Z   INFO - MODIFIED local-path-provisioner-957fdf8bc-q9ttw
2023-04-29T16:25:03.009193Z   INFO - MODIFIED local-path-provisioner-957fdf8bc-q9ttw
2023-04-29T16:25:32.277869Z   INFO - MODIFIED local-path-provisioner-957fdf8bc-z6m4k
2023-04-29T16:25:33.006053Z   INFO - MODIFIED local-path-provisioner-957fdf8bc-z6m4k
2023-04-29T16:25:33.019123Z   INFO - MODIFIED local-path-provisioner-957fdf8bc-z6m4k
2023-04-29T16:25:33.031196Z   INFO - DELETED local-path-provisioner-957fdf8bc-z6m4k
2023-04-29T16:35:33.067459Z  ERROR - kube.transport: End of file reached
2023-04-29T16:35:33.067473Z  TRACE - kube.transport: End of file reached
End of file reached (IO::EOFError)
  from /opt/homebrew/Cellar/crystal/1.7.2/share/crystal/src/io.cr:841:31 in 'read_line:chomp'
  from /opt/homebrew/Cellar/crystal/1.7.2/share/crystal/src/http/content.cr:205:7 in 'read_chunk_size'
  from /opt/homebrew/Cellar/crystal/1.7.2/share/crystal/src/http/content.cr:187:26 in 'next_chunk'
  from /opt/homebrew/Cellar/crystal/1.7.2/share/crystal/src/http/content.cr:153:7 in 'peek'
  from /opt/homebrew/Cellar/crystal/1.7.2/share/crystal/src/io.cr:656:37 in 'gets'
  from /opt/homebrew/Cellar/crystal/1.7.2/share/crystal/src/io.cr:629:5 in 'gets'
  from /opt/homebrew/Cellar/crystal/1.7.2/share/crystal/src/io.cr:599:5 in 'gets'
  from /opt/homebrew/Cellar/crystal/1.7.2/share/crystal/src/io.cr:598:3 in 'gets'
  from src/kube/transport/requests.cr:130:27 in '_watch_request'
  from src/kube/transport/requests.cr:121:7 in '->'
  from /opt/homebrew/Cellar/crystal/1.7.2/share/crystal/src/fiber.cr:146:11 in 'run'
  from /opt/homebrew/Cellar/crystal/1.7.2/share/crystal/src/fiber.cr:98:34 in '->'

2023-04-29T16:35:33.068967Z  DEBUG - http.client: Performing request -- method: "GET", host: "ubu", port: 54977, resource: "/api/v1/namespaces/kube-system/pods?watch=true"
2023-04-29T16:35:33.385208Z   INFO - ADDED coredns-77ccd57875-q8lrh
2023-04-29T16:35:33.387815Z   INFO - ADDED helm-install-traefik-crd-vcl4j
2023-04-29T16:35:33.387819Z   INFO - ADDED helm-install-traefik-ntxns
2023-04-29T16:35:33.388450Z   INFO - ADDED svclb-traefik-ead43597-ph2qt
2023-04-29T16:35:33.390877Z   INFO - ADDED metrics-server-54dc485875-b7576
2023-04-29T16:35:33.390881Z   INFO - ADDED traefik-84745cf649-92pgw
2023-04-29T16:35:33.391352Z   INFO - ADDED local-path-provisioner-957fdf8bc-q9ttw
```

However, i ran it for about 2 hours so far and i dont see any hanging yet. Im always able to get an event when i kick a pod.

I dont like that it reconnects every 10 mins, so ill keep looking at that.

**Comment by vitobotta** [comment]
@kalinon which cluster are you testing with? I think that some versions and flavors of kubernetes have different timeouts etc that affect the watch. 

In my case with a k3s cluster I don't even see EOFErrors. No errors at all actually. It just stops reacting to events or something like that. Any ideas of what I can try to help investigate?

**Comment by vitobotta** [comment]
I also was looking into the timeout setting for the `watch` method that should be an integer according to lib/kube-client/lib/kube-client/src/kube/resource_client.cr, but if I try setting it to a number that this triggers an error with `make_query` since numbers are not accepted. What does this timeout do exactly?

**Comment by kalinon** [comment]
I was getting the 10 min EOF errors against a k3d cluster, but i am getting the handing issue against a EKS cluster.

Im not exactly sure what the "timeoutSeconds" arg does. but looking into it, it seems perhaps this watch should be a websocket and not use `HTTP::Client`

I will experiment with that.

**Comment by vitobotta** [comment]
I am now trying to adapt a "solution" that worked with Ruby during my tests, which is to interrupt execution after 3 minutes and restart the watch. This is because with some clusters like AKS there are problems with watches lasting longer than 4 minutes or something like that.

I am trying this now just out of curiosity but it doesn't work:

```crystal
  private def watch_backups
    @resource_version = last_resource_version

    Log.info { "Watching backups from resource version #{resource_version}" }

    sig = Channel(Nil).new

    spawn do
      sleep 10.seconds
      sig.send nil
    end

    resource_client = api_client.api("velero.io/v1").resource("backups", namespace: velero_namespace)
    channel = resource_client.watch(resource_version: resource_version)
    timeout = false

    until channel.closed?
      timeout = select
      when event = channel.receive
        false
      when sig.receive
        true
      end

      if timeout || event.is_a?(Kube::Error::API)
        channel.close
        raise APIError.new(message = "API error")
      elsif event.is_a? K8S::Kubernetes::WatchEvent(K8S::Velero::V1::Backup)
        Event.new(event).notify
        @resource_version = event.object["metadata"].as(Hash)["resourceVersion"].to_s
        update_configmap
      end
    end
  end
```

I get `Error: undefined method 'receive_select_action' for Kube::WatchChannel(K8S::Api::Admissionregistration::V1::MutatingWebhookConfiguration)`

**Comment by vitobotta** [comment]
That causes other exceptions with API requests when the channel is closed. Any better approach?

**Comment by kalinon** [comment]
@vitobotta i found the bug on my side, i never raise an exception if the watch connection closes. Doing a wireshark, i was able to see that the connection actually being closed.

![Screenshot 2023-04-29 at 2 47 12 PM](https://user-images.githubusercontent.com/5629164/235319206-6bc062a5-a9b4-4611-bec5-04b4b4621e9d.png)

Working on a fix now

**Comment by vitobotta** [comment]
Awesome, looking forward to testing the fix!! 🙏

**Comment by kalinon** [comment]
@vitobotta you can test this fix on the `kalinon/issue12` branch.

Here's my sample: 

```
resource_client = client.api("v1").resource("pods", namespace: "kube-system")

resource_client.watch do |event|
  obj = event.object.as(K8S::Api::Core::V1::Pod)
  Log.info { "#{event.type} #{obj.metadata.try &.name}" }
end
```

Turns out passing the timeout will cause it close that connection after that many seconds. So you could test abrupt disconnects via `watch(timeout: 30)`

im gonna let my test run for a few hours before cutting a new release. Great find!

**Comment by vitobotta** [comment]
Sounds awesome. Will try it right away and report back. Thanks!

**Comment by vitobotta** [comment]
The timeout works like a charm. Because of the issues with AKS I have now set a timeout of 3 minutes and wrapped my code in a loop so it restarts the watch. I have scheduled Velero backups every 6 hours now so there is a good time between events. Fingers crossed 👍

**Comment by kalinon** [comment]
@vitobotta ive dug deeper and implemented a few things if you wanted to give it a try. A new A Kube::Error::WatchClosed error will be returned if the watch stream has been closed, which also contains the last `resourceVersion` so you can reconnect to the watch stream. Passing the last known `resourceVersion` will pick up the watch where it left off, without repeat events.

Also, ive added an `auto_resume` flag when using `watch` with a block, which will keep your watch going.

```
client = Kube::Client.autoconfig
resource_client = client.api("v1").resource("pods", namespace: "kube-system")

begin
  resource_client.watch(timeout: 10, auto_resume: true) do |event|
    obj = event.object.as(K8S::Api::Core::V1::Pod)
    Log.info { "#{event.type} #{obj.metadata.try &.name}" }
  end
rescue ex : Kube::Error::WatchClosed
  Log.info &.emit "Watch closed", {message: ex.message, resource_version: ex.resource_version}
end
```

Check out the PR #14

**Comment by vitobotta** [comment]
I'll follow up in the PR 👍
