### ISSUE TITLE
Error casting from generic resource to specific resource

### ISSUE THREAD

**Issue by emeraldarcher** [spoved/kube-client.cr#15]
Looking at the examples the pattern seems to be to get the generic resource type from the resource client and then use `.as` to cast to the actual resource type. I'm attempting to do this with batch jobs but get an error casting.

`Cast from K8S::Kubernetes::Resource::Generic to K8S::Api::Batch::V1::Job failed`

```
job_resource_client = @@kube_client.api("batch/v1").resource("jobs/status", @@K8S_NAMESPACE)
job = job_resource_client.get(job_name).as(K8S::Api::Batch::V1::Job)
```

I used to be able to do this by casting the resource client to a job resource client like so: `job_resource_client = @@kube_client.api("batch/v1").resource("jobs/status", @@K8S_NAMESPACE).as(Kube::ResourceClient(K8S::Api::Batch::V1::Job))` but that doesn't work anymore. Any ideas/help would be appreciated.

**Comment by kalinon** [comment]
what version of crystal are you using?

**Comment by emeraldarcher** [comment]
I'm using 1.9.2

**Comment by kalinon** [comment]
@emeraldarcher i believe your issue is that you are trying to cast a `job/status` into a `job` resource client. 

```
@@kube_client.api("batch/v1").resource("jobs/status", @@K8S_NAMESPACE) #=> #<Kube::ResourceClient(K8S::Kubernetes::Resource::Generic):0x103a8e2d0
```
vs

```
@@kube_client.api("batch/v1").resource("jobs", @@K8S_NAMESPACE) #=> #<Kube::ResourceClient(K8S::Api::Batch::V1::Job):0x1059062d0 
```

`jobs/status` will be a Generic resource.

**Comment by emeraldarcher** [comment]
Ah, okay that makes sense. I'll update accordingly, thank you.
